version: '2'
services:
    app:
        build:
            context: ../..
            dockerfile: docker/dev/Dockerfile
        volumes:
            - ../..:/code
        ports:
            - "8000:8000"
        depends_on:
            - nodejs
    nodejs:
        image: janmarthedal/dtpnodejs
        build:
            context: ../../javascript
            dockerfile: Dockerfile
