version: '2'
services:
    app:
        image: janmarthedal/dtp
        build:
            context: ..
            dockerfile: docker/Dockerfile
        depends_on:
            - nodejs
        external_links:
            - db
    nodejs:
        image: janmarthedal/dtpnodejs
        build:
            context: ../javascript
            dockerfile: Dockerfile
    db:
        image: mysql
        volumes:
            - ../db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: orangebear
            MYSQL_DATABASE: dtp
        command: --character-set-server=utf8 --collation-server=utf8_general_ci
