version: '2'
services:
    app:
        image: mathitems-app
        build:
            context: ../..
            dockerfile: docker/prod/Dockerfile
        volumes:
            - ../../media-files:/code/media-files
        depends_on:
            - nodejs
        external_links:
            - db
            - elasticsearch
    nodejs:
        image: mathitems-node
        build:
            context: ../../javascript
            dockerfile: Dockerfile
    db:
        image: mysql
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: orangebear
            MYSQL_DATABASE: dtp
        command: --character-set-server=utf8 --collation-server=utf8_bin
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
        container_name: elasticsearch
        environment:
            - cluster.name=cluster
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - xpack.monitoring.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: 1g
        cap_add:
            - IPC_LOCK
        volumes:
            - es_data:/usr/share/elasticsearch/data

volumes:
    db_data:
        driver: local
    es_data:
        driver: local
